sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.27.1
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose headless


before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev;
    fi
